spring:
  application:
    name: Etudiant
  config:
    import:
    - configserver:http://localhost:8788
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/etudiant
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
